version: '3.9'

services:
  # mysqldb:
  #   image: mysql:8.0.31
  #   restart: unless-stopped
  #   env_file: ./.env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
  #     - MYSQL_DATABASE=$DB_DATABASE
  #   expose:
  #     - $DB_PORT
  #   volumes:
  #     - db:/var/lib/mysql
  redis:
    image: 'redis/redis-stack-server'
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    environment:
    - REDIS_ARGS=--save 1200 32
    volumes:
    - redis_data:/data:rw
    ports:
    - 6379:6379
    expose:
    - 6379
    restart: unless-stopped
  app:
    depends_on:
      - redis
    build: 
      context: .
      dockerfile: Dockerfile
    # network_mode: "host"  
    env_file: ./.env
    # environment:
      # - DB_HOST=mysqldb
      # - DB_TYPE=mysql
      # - DB_USERNAME=$DB_USERNAME
      # - DB_PASSWORD=$DB_PASSWORD
      # - DB_DATABASE=$DB_DATABASE
      # - DB_PORT=$DB_PORT
      # - ADMIN_PASSWORD=$ADMIN_PASSWORD
      # - JWT_SECRET=$JWT_SECRET
      # - JWT_SECRET_PREV=$JWT_SECRET_PREV
      # - SALT_ROUNDS=$SALT_ROUNDS
      # - SERVER_PORT=$SERVER_PORT
      # - PUBLIC_IMAGES =$PUBLIC_IMAGES
    ports:
      - 0.0.0.0:$PORT:$PORT
    stdin_open: true
    tty: true
    

volumes:
  redis_data: